api/config/routes.rb
Api::Application.routes.draw do
  resources :trips do
    member do
      get :mapview
      get :points
      get :directions
      get :steps
    end
  end

  root :to => "trips#index"

end

api/app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :leg
end

api/app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :trip
  has_one :next_step, :class_name => 'Step', :foreign_key => :id
  has_one :previous_step, :class_name => 'Step', :foreign_key => :id
  has_one :start_point, :class_name => 'Point', :primary_key => :start_point_id, :foreign_key => :id
  has_one :end_point, :class_name => 'Point', :primary_key => :start_point_id, :foreign_key => :id
  
  before_destroy :cleanup
  
  def cleanup
    points.each &:destroy
    # end_point.destroy
    # start_point.destroy
    previous_step.next_step = next_step if previous_step
    next_step.previous_step = previous_step if next_step
  end
  
  def points
    [start_point, end_point]
  end
end

api/app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :steps, :dependent => :destroy
  
  validates_presence_of :origin, :destination, :name

  after_create :route
  
  def first_step
    steps.find_by_previous_step_id(nil)
  end
  
  def points
    steps.collect{|l| l.points}.flatten
  end
  
  attr_accessor :center_point
  def center
    return @center_point if @center_point
    start = self.steps.find_by_previous_step_id(nil).start_point
    puts "Start: #{start.inspect}"
    finish = self.steps.find_by_next_step_id(nil).end_point
    puts "Finish: #{finish.inspect}"
    
    avg_lat = (start.latitude.to_f + finish.latitude.to_f) / 2.0
    avg_long = (start.longitude.to_f + finish.longitude.to_f) / 2.0
    
    @center_point = {:latitude => avg_lat, :longitude => avg_long}
  end
  
  def route #(origin,destination,name)
    
    # get json from google maps api
    response = JSON.parse(
      RestClient.get "http://maps.googleapis.com/maps/api/directions/json", 
        {:accept => :json, 
         :params => {
           :origin => self.origin, 
           :destination => self.destination, 
           :sensor => false }
        }
      )
      
    route = response['routes'].first
    leg = route['legs'].first
    steps = leg['steps']
    prev_step = nil
    steps.each do |step|
      new_step = Step.create(
        :trip_id => self.id,
        :start_point_id => Point.create(
          :latitude => step['start_location']['lat'],
          :longitude => step['start_location']['lng']
        ).id,
        :end_point_id => Point.create(
          :latitude => step['end_location']['lat'],
          :longitude => step['end_location']['lng']
        ).id,
        :instructions => step['html_instructions'],
        :distance => step['distance']['text'],
        :path => step['polyline']['points']
      )
      new_step.update_attribute(:previous_step_id,prev_step.id) if prev_step
      prev_step.update_attribute(:next_step_id,new_step.id) if prev_step 
      self.steps << new_step
      prev_step = new_step
    end
  end
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

api/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  before_filter :find_trip, :except => [:index, :new, :create]
  # GET /trips
  # GET /trips.xml
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.xml
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    # @trip.steps.each do |step|
    #   marker = Cartographer::Gmarker.new(
    #     :name => "marker",
    #     :marker_type => "Building",
    #     :position => [step.start_point.latitude, step.start_point.longitude],
    #     :info_window_url => "/",
    #     :icon => @icon)
    #   @map.markers << marker
    # end
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @trip }
    end

  end
  
  def mapview
    respond_to do |format|
      format.html  { render :layout => 'map_page'}
    end
  end
  
  def steps
    respond_to do |format|
    format.json  { render :json => @trip.steps }
    end
  end
  
  def directions
    respond_to do |format|
      format.html
      format.json {render :json => @trip.steps.map {|s| s.instructions}} 
    end
  end

  def points
    respond_to do |format|
      format.json { render :json => @trip.points }
    end
  end

  # GET /trips/new
  # GET /trips/new.xml
  def new
    @trip = Trip.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trip }
    end
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.xml
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to(@trip, :notice => 'Trip was successfully created.') }
        format.xml  { render :xml => @trip, :status => :created, :location => @trip }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.xml
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to(@trip, :notice => 'Trip was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.xml
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to(trips_url) }
      format.xml  { head :ok }
    end
  end
  
  def map
    @trip = Trip.find(params[:id])
    @map = Cartographer::Gmap.new( 'map' )
    @map.zoom = :bound
    @icon = Cartographer::Gicon.new()
    @map.icons <<  @icon
    @trip.steps.each do |step|
      marker = Cartographer::Gmarker.new(
        :name => "marker",
        :marker_type => "Building",
        :position => [step.start_point.latitude.to_f, step.start_point.longitude.to_f],
        :icon => @icon)
      @map.markers << marker
    end
  end

private
 
  def find_trip
    @trip = Trip.find(params[:id])
  end

end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/trips_helper.rb
module TripsHelper
end

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Api</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
</head>
<body>

<%= yield %>

</body>
</html>

api/app/views/layouts/map_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MAP</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"></script>
</head>
<body onload="initialize();">

<%= yield %>

<div id="map_canvas" style="width:100%; height:100%"></div>

</body>
</html>

api/app/views/steps/_step.haml
.step
  .distance
    Distance:
    = step.distance
  .instructions
    = step.instructions.html_safe

api/app/views/trips/_actions.html.haml
.actions
  = link_to 'Get Directions', directions_trip_path(@trip)
  = link_to 'See the Map', mapview_trip_path(@trip)
  = link_to 'Back to the Index', trips_path 

api/app/views/trips/_form.html.haml
= form_for(@trip) do |f|
  -if @trip.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@trip.errors.count, "error")
        prohibited this trip from being saved:

      %ul
        - @trip.errors.full_messages.each do |msg|
          %li= msg
  =f.label :name
  =f.text_field :name
  %br
  =f.label :origin
  =f.text_field :origin
  %br
  =f.label :destination
  =f.text_field :destination
  %br
  %div.actions
    = f.submit

api/app/views/trips/_map.html.erb
<script type="text/javascript">
  function initialize() {
    // get map data;
    <%- start = trip.first_step.start_point %>
    var latlng = new google.maps.LatLng(<%= trip.center[:latitude] %>, <%= trip.center[:longitude] %>);
    var myOptions = {
      zoom: 7,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"),
        myOptions);
        
    var ctaLayer = new google.maps.KmlLayer('http://www.weather.gov/forecasts/xml/sample_products/browser_interface/ndfdXMLclient.php?gmlListLatLon=35.246741,-80.842896+36.09239,-79.792328+36.09239,-79.792328+37.542979,-77.469092+38.895112,-77.036366&featureType=Ndfd_KmlPoint&startTime=2011-05-15T12:00:00&endTime=2011-05-16T17:00:00&compType=Between&propertyName=maxt,mint,sky,wx,icons',
      {suppressInfoWindows: true});
    ctaLayer.setMap(map);
    
    var markers = [];
    var lines = []
    <%- counter = 0 -%>
    <%- trip.steps.each do |s| -%>
      markers[<%= counter -%>] = new google.maps.Marker({
            position: new google.maps.LatLng(<%= s.start_point.latitude -%>, <%=s.start_point.longitude -%>),
            map: map, 
            title:"Next Turn"
        });
      lines[<%= counter -%>] = new google.maps.Polyline({
          path: google.maps.geometry.encoding.decodePath('<%=s.path-%>'),
          strokeColor: "#FF0000",
          strokeOpacity: 1.0,
          strokeWeight: 2
        });
      lines[<%= counter -%>].setMap(map);
        
      <%- counter += 1 -%>
    <%- end -%>
  
  }

</script>

api/app/views/trips/_trip.haml
.trip
  .name
    = trip.name
  .from
    = trip.origin
  .to
    = trip.destination
  .actions
    = link_to "view", trip_path(trip)
    = link_to 'edit', edit_trip_path(trip)
    = link_to "delete", trip_path(trip), :method => :delete, :confirm => true

api/app/views/trips/directions.html.haml
%p#notice= notice

%h1
  Trip:
  = @trip.name

%h2
  From:
  = @trip.origin

%h2
  To:
  = @trip.destination

= render @trip.steps

= render :partial => 'trips/actions', :locals => {:trip => @trip}

api/app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

api/app/views/trips/index.html.haml
%h1 Listing trips

= render @trips

= link_to 'New Trip', new_trip_path

api/app/views/trips/mapview.html.haml
%p#notice= notice

%h1
  Trip:
  = @trip.name

%h2
  From:
  = @trip.origin

%h2
  To:
  = @trip.destination

= render :partial => 'map', :locals => {:trip => @trip}

= render :partial => 'trips/actions', :locals => { :trip => @trip} 

api/app/views/trips/new.html.haml
%h1 New trip

= render 'form'

= link_to 'Back', trips_path

api/app/views/trips/show.html.haml
%p#notice= notice

%h1
  Trip:
  = @trip.name

%h2
  From:
  = @trip.origin

%h2
  To:
  = @trip.destination

= render :partial => 'trips/actions', :locals => {:trip => @trip}